"""Response Classifier - categorizes HTTP responses before agent interpretation.

Prevents the agent from:
- Treating WAF block pages as real 403 Forbidden
- Treating rate limiting as target being down
- Treating auth redirects as errors
- Acting on empty output from blocked tools

Every response gets a classification before the agent sees it.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any


@dataclass
class ResponseClassification:
    """Classification result for an HTTP response."""

    category: str        # real_content | waf_block | rate_limited | auth_redirect | dead_host | tool_error | empty_suspicious
    waf_vendor: str      # cloudflare | akamai | aws_waf | imperva | sucuri | f5 | modsecurity | unknown | none
    confidence: float    # 0-1
    recommendation: str  # proceed | backoff_30s | backoff_60s | skip_target | use_different_tool | investigate
    details: str         # Human-readable explanation


class ResponseClassifier:
    """Classify HTTP responses and tool output before agent interpretation."""

    # WAF detection: header names (lowercased) that indicate a specific vendor.
    WAF_HEADER_SIGNATURES: dict[str, list[str]] = {
        "cloudflare": [
            "cf-ray",
            "cf-cache-status",
            "cf-connecting-ip",
            "cf-worker",
        ],
        "akamai": [
            "x-akamai-transformed",
            "x-akamai-session-outgoing",
            "x-akamai-origin-hop",
            "akamai-grn",
            "x-check-cacheable",
        ],
        "aws_waf": [
            "x-amzn-requestid",
            "x-amz-cf-id",
            "x-amzn-trace-id",
            "x-amz-apigw-id",
        ],
        "imperva": [
            "x-iinfo",
            "x-cdn-forward",
        ],
        "sucuri": [
            "x-sucuri-id",
            "x-sucuri-cache",
        ],
        "f5": [
            "x-wa-info",
            "bigipserver",
            "x-cnection",
        ],
        "modsecurity": [
            "x-modsecurity-action",
        ],
    }

    # Server header values that indicate a WAF.
    WAF_SERVER_VALUES: dict[str, list[str]] = {
        "cloudflare": ["cloudflare"],
        "sucuri": ["sucuri/"],
        "imperva": ["incapsula"],
        "f5": ["big-ip", "bigip"],
    }

    # Cookie name prefixes that indicate a WAF session.
    WAF_COOKIE_SIGNATURES: dict[str, list[str]] = {
        "cloudflare": ["__cf_bm", "__cflb", "cf_clearance"],
        "imperva": ["incap_ses_", "visid_incap_"],
        "akamai": ["ak_bmsc", "bm_sz"],
        "f5": ["ts", "tsrce"],  # short names, only used as tiebreaker
    }

    # Body fragments (lowercase) that indicate a WAF block page.
    WAF_BODY_SIGNATURES: dict[str, list[str]] = {
        "cloudflare": [
            "attention required",
            "cloudflare",
            "error code: 1020",
            "ray id:",
            "cf-error-details",
            "ddos protection by cloudflare",
            "just a moment",
            "enable javascript and cookies",
        ],
        "akamai": [
            "access denied",
            "reference #",
            "akamai",
            "the requested url was rejected by an automated security check",
        ],
        "aws_waf": [
            "request blocked",
            "aws waf",
            "403 forbidden",
        ],
        "imperva": [
            "the requested url was rejected",
            "incapsula",
            "incident id:",
            "powered by imperva",
        ],
        "sucuri": [
            "access denied - sucuri website firewall",
            "sucuri website firewall",
            "generated by wordfence",  # Sucuri partner product
        ],
        "wordfence": [
            "your access to this site has been limited",
            "wordfence",
            "generated by wordfence",
        ],
        "f5": [
            "the requested url was rejected",
            "please consult with your administrator",
            "your support id is:",
        ],
        "modsecurity": [
            "not acceptable!",
            "406 not acceptable",
            "mod_security",
            "modsecurity",
        ],
    }

    # Patterns in a body that signal a generic block even with no vendor match.
    GENERIC_BLOCK_PATTERNS: list[re.Pattern[str]] = [
        re.compile(r"your\s+ip\s+(?:address\s+)?(?:has\s+been\s+)?blocked", re.IGNORECASE),
        re.compile(r"suspicious\s+activity\s+detected", re.IGNORECASE),
        re.compile(r"security\s+check", re.IGNORECASE),
        re.compile(r"automated\s+(?:tool|bot|request|access)", re.IGNORECASE),
        re.compile(r"challenge.*required", re.IGNORECASE),
        re.compile(r"captcha", re.IGNORECASE),
    ]

    # Patterns that indicate the redirect target is a login/auth page.
    AUTH_REDIRECT_PATTERNS: list[re.Pattern[str]] = [
        re.compile(r"/(?:login|signin|sign-in|auth|authenticate|sso|oauth)", re.IGNORECASE),
        re.compile(r"[?&](?:redirect|return|next|returnTo|redirect_uri)=", re.IGNORECASE),
        re.compile(r"accounts?\.", re.IGNORECASE),
        re.compile(r"/session", re.IGNORECASE),
    ]

    # Tool stderr patterns that indicate permanent vs transient errors.
    TOOL_PERMANENT_ERRORS: list[re.Pattern[str]] = [
        re.compile(r"no such file or directory", re.IGNORECASE),
        re.compile(r"command not found", re.IGNORECASE),
        re.compile(r"executable file not found", re.IGNORECASE),
        re.compile(r"unknown flag", re.IGNORECASE),
        re.compile(r"invalid (?:flag|argument|option|syntax)", re.IGNORECASE),
        re.compile(r"unrecognized (?:flag|option)", re.IGNORECASE),
        re.compile(r"error: required flag", re.IGNORECASE),
        re.compile(r"schema (?:validation )?error", re.IGNORECASE),
        re.compile(r"permission denied", re.IGNORECASE),
    ]

    TOOL_TRANSIENT_ERRORS: list[re.Pattern[str]] = [
        re.compile(r"timed? ?out", re.IGNORECASE),
        re.compile(r"connection (?:refused|reset|timed out)", re.IGNORECASE),
        re.compile(r"network (?:error|unreachable)", re.IGNORECASE),
        re.compile(r"dial tcp.*i/o timeout", re.IGNORECASE),
        re.compile(r"temporary failure", re.IGNORECASE),
        re.compile(r"(?:read|write) tcp.*timeout", re.IGNORECASE),
        re.compile(r"context deadline exceeded", re.IGNORECASE),
        re.compile(r"too many open files", re.IGNORECASE),
    ]

    def classify_http(
        self,
        status_code: int,
        headers: dict[str, str],
        body: str,
        response_time_ms: float = 0,
    ) -> ResponseClassification:
        """Classify an HTTP response.

        Checks in order:
        1. WAF block detection (header + body signatures)
        2. Rate limiting (429, Retry-After present)
        3. Auth redirect (3xx to /login or similar)
        4. Dead host / empty response
        5. Real content
        """
        lower_headers = {k.lower(): v.lower() for k, v in headers.items()}
        lower_body = body.lower() if body else ""

        # ---- 1. WAF block detection ----
        waf_vendor, waf_confidence = self.detect_waf(headers, body)

        # A 403/406/429/503 with a WAF vendor signature is almost certainly a block.
        waf_status_codes = {403, 406, 429, 503}
        if waf_vendor != "none":
            if status_code in waf_status_codes or waf_confidence >= 0.7:
                return ResponseClassification(
                    category="waf_block",
                    waf_vendor=waf_vendor,
                    confidence=waf_confidence,
                    recommendation="use_different_tool",
                    details=(
                        f"{waf_vendor.upper()} WAF block detected (status {status_code}, "
                        f"confidence {waf_confidence:.0%}). "
                        "This is NOT a real server response. "
                        "Try different encoding, reduce request rate, or skip this target."
                    ),
                )

        # ---- 2. Rate limiting ----
        retry_after = lower_headers.get("retry-after", "")
        if status_code == 429 or (status_code == 503 and retry_after):
            backoff = 60
            if retry_after.isdigit():
                backoff = max(30, min(300, int(retry_after)))
            return ResponseClassification(
                category="rate_limited",
                waf_vendor="none",
                confidence=0.95,
                recommendation="backoff_60s",
                details=(
                    f"Rate limited (status {status_code}"
                    + (f", Retry-After: {retry_after}s" if retry_after else "")
                    + f"). Back off {backoff}s before retrying."
                ),
            )

        # ---- 3. Auth redirect ----
        if status_code in (301, 302, 303, 307, 308):
            location = lower_headers.get("location", "")
            for pattern in self.AUTH_REDIRECT_PATTERNS:
                if pattern.search(location):
                    return ResponseClassification(
                        category="auth_redirect",
                        waf_vendor="none",
                        confidence=0.9,
                        recommendation="investigate",
                        details=(
                            f"Auth redirect detected (status {status_code} -> {location}). "
                            "Target requires authentication. "
                            "Check if session cookies are needed or if the endpoint is behind SSO."
                        ),
                    )
            # Generic redirect (not auth-looking)
            return ResponseClassification(
                category="real_content",
                waf_vendor="none",
                confidence=0.8,
                recommendation="proceed",
                details=f"Redirect to {location} (status {status_code}) - follow the chain.",
            )

        # ---- 4. Dead host / timeout ----
        if status_code == 0 or (not body and response_time_ms > 10_000):
            return ResponseClassification(
                category="dead_host",
                waf_vendor="none",
                confidence=0.85,
                recommendation="skip_target",
                details=(
                    f"No response received (status {status_code}, "
                    f"elapsed {response_time_ms:.0f}ms). "
                    "Host may be down, filtered, or unreachable."
                ),
            )

        # ---- 5. Empty response (suspicious when status 200) ----
        if not body.strip() and status_code == 200:
            return ResponseClassification(
                category="empty_suspicious",
                waf_vendor=waf_vendor,
                confidence=0.6,
                recommendation="investigate",
                details=(
                    "200 OK with empty body. "
                    "This may be a silent WAF block, CDN caching issue, or legitimately empty endpoint. "
                    "Verify with a browser request."
                ),
            )

        # ---- 6. Generic block body (no vendor matched) ----
        for pattern in self.GENERIC_BLOCK_PATTERNS:
            if pattern.search(body):
                return ResponseClassification(
                    category="waf_block",
                    waf_vendor="unknown",
                    confidence=0.65,
                    recommendation="use_different_tool",
                    details=(
                        f"Generic security block detected in response body (status {status_code}). "
                        "Vendor unknown but automated-access filtering is active."
                    ),
                )

        # ---- 7. Real content ----
        return ResponseClassification(
            category="real_content",
            waf_vendor="none",
            confidence=0.9,
            recommendation="proceed",
            details=f"Real server response (status {status_code}, {len(body)} bytes). Proceed.",
        )

    def classify_tool_output(
        self,
        tool: str,
        returncode: int,
        stdout: str,
        stderr: str,
        elapsed_ms: float = 0,
    ) -> ResponseClassification:
        """Classify raw tool execution output.

        Three error classes:
        - TRANSIENT: timeout, network error -> retry with backoff
        - PERMANENT: tool not found, wrong flags, schema error -> use alternative
        - EMPTY: tool exited 0 but no output -> likely WAF block, investigate
        """
        combined_err = (stderr or "").lower()
        combined_out = (stdout or "").strip()

        # ---- Tool not found (permanent, no point retrying) ----
        if returncode == 127 or "command not found" in combined_err or "no such file" in combined_err:
            return ResponseClassification(
                category="tool_error",
                waf_vendor="none",
                confidence=0.99,
                recommendation="use_different_tool",
                details=(
                    f"Tool '{tool}' not found on this system. "
                    "Use an available alternative or install the tool."
                ),
            )

        # ---- Permanent errors (wrong flags, schema, permissions) ----
        for pattern in self.TOOL_PERMANENT_ERRORS:
            if pattern.search(combined_err):
                return ResponseClassification(
                    category="tool_error",
                    waf_vendor="none",
                    confidence=0.9,
                    recommendation="use_different_tool",
                    details=(
                        f"Permanent error from '{tool}' (exit {returncode}): "
                        f"{stderr[:200].strip()}. "
                        "Do not retry with same flags. Fix the command or use an alternative."
                    ),
                )

        # ---- Transient errors (network / timeout) ----
        for pattern in self.TOOL_TRANSIENT_ERRORS:
            if pattern.search(combined_err) or (returncode == -1 and "timed out" in combined_err):
                return ResponseClassification(
                    category="tool_error",
                    waf_vendor="none",
                    confidence=0.85,
                    recommendation="backoff_30s",
                    details=(
                        f"Transient error from '{tool}' (exit {returncode}): "
                        f"{stderr[:200].strip()}. "
                        "Wait 30s and retry once. If it fails again, skip this target."
                    ),
                )

        # ---- Generic non-zero exit with stderr ----
        if returncode != 0 and combined_err:
            return ResponseClassification(
                category="tool_error",
                waf_vendor="none",
                confidence=0.75,
                recommendation="investigate",
                details=(
                    f"'{tool}' exited {returncode}: {stderr[:200].strip()}. "
                    "Check the command and parameters before retrying."
                ),
            )

        # ---- Suspicious empty output (exit 0, no stdout) ----
        if returncode == 0 and not combined_out:
            # Check if stderr has WAF-like content
            waf_vendor, waf_confidence = self.detect_waf({}, stderr + stdout)
            if waf_vendor != "none":
                return ResponseClassification(
                    category="empty_suspicious",
                    waf_vendor=waf_vendor,
                    confidence=waf_confidence,
                    recommendation="use_different_tool",
                    details=(
                        f"'{tool}' exited 0 with no output. "
                        f"{waf_vendor.upper()} WAF signatures detected in stderr. "
                        "Requests are being silently blocked. Try manual curl to confirm."
                    ),
                )
            return ResponseClassification(
                category="empty_suspicious",
                waf_vendor="none",
                confidence=0.7,
                recommendation="investigate",
                details=(
                    f"'{tool}' exited 0 with no output and no errors. "
                    "This is suspicious: target may be returning empty responses or WAF is silently blocking. "
                    "Verify manually with curl before assuming no findings."
                ),
            )

        # ---- Normal output ----
        return ResponseClassification(
            category="real_content",
            waf_vendor="none",
            confidence=0.9,
            recommendation="proceed",
            details=f"'{tool}' completed successfully (exit {returncode}, {len(combined_out)} chars output).",
        )

    def detect_waf(self, headers: dict[str, str], body: str) -> tuple[str, float]:
        """Detect WAF vendor from headers and body. Returns (vendor, confidence)."""
        scores: dict[str, float] = {}
        lower_headers = {k.lower(): v.lower() for k, v in headers.items()}
        lower_body = (body or "").lower()

        # ---- Header-based detection ----
        for vendor, header_names in self.WAF_HEADER_SIGNATURES.items():
            for header in header_names:
                if header in lower_headers:
                    scores[vendor] = scores.get(vendor, 0.0) + 0.4

        # ---- Server header value ----
        server_val = lower_headers.get("server", "")
        for vendor, server_fragments in self.WAF_SERVER_VALUES.items():
            for fragment in server_fragments:
                if fragment in server_val:
                    scores[vendor] = scores.get(vendor, 0.0) + 0.35

        # ---- Cookie-based detection ----
        set_cookie = lower_headers.get("set-cookie", "")
        for vendor, cookie_names in self.WAF_COOKIE_SIGNATURES.items():
            for cookie in cookie_names:
                if cookie in set_cookie:
                    scores[vendor] = scores.get(vendor, 0.0) + 0.25

        # ---- Body-based detection ----
        for vendor, body_fragments in self.WAF_BODY_SIGNATURES.items():
            for fragment in body_fragments:
                if fragment in lower_body:
                    scores[vendor] = scores.get(vendor, 0.0) + 0.3

        if not scores:
            return "none", 0.0

        best_vendor = max(scores, key=lambda v: scores[v])
        raw_confidence = min(scores[best_vendor], 1.0)
        return best_vendor, raw_confidence

    def get_backoff_seconds(self, classification: ResponseClassification) -> int:
        """Get recommended backoff time in seconds based on classification."""
        mapping = {
            "backoff_30s": 30,
            "backoff_60s": 60,
            "skip_target": 0,
            "proceed": 0,
            "use_different_tool": 0,
            "investigate": 0,
        }
        return mapping.get(classification.recommendation, 0)

    def format_for_agent(self, classification: ResponseClassification) -> str:
        """Format classification as an actionable string for the agent.

        Examples:
          [WAF BLOCK - Cloudflare] This is not a real 403. Cloudflare is blocking
          your request. DO NOT retry the same payload. Options: try different
          encoding, reduce request rate, or skip this target.

          [RATE LIMITED] Target returned 429. Back off 60s before retrying.
        """
        category_labels = {
            "waf_block": "WAF BLOCK",
            "rate_limited": "RATE LIMITED",
            "auth_redirect": "AUTH REDIRECT",
            "dead_host": "DEAD HOST",
            "tool_error": "TOOL ERROR",
            "empty_suspicious": "EMPTY/SUSPICIOUS",
            "real_content": "REAL CONTENT",
        }

        label = category_labels.get(classification.category, classification.category.upper())

        if classification.waf_vendor not in ("none", "unknown", ""):
            label = f"{label} - {classification.waf_vendor.upper()}"
        elif classification.waf_vendor == "unknown":
            label = f"{label} - UNKNOWN VENDOR"

        action_hints = {
            "proceed": "Proceed with analysis.",
            "backoff_30s": "WAIT 30 seconds before the next request.",
            "backoff_60s": "WAIT 60 seconds before the next request.",
            "skip_target": "SKIP this target - do not waste further requests on it.",
            "use_different_tool": "DO NOT retry with the same tool or payload. Use curl or a different approach.",
            "investigate": "Investigate manually before proceeding.",
        }
        action = action_hints.get(classification.recommendation, classification.recommendation)

        return f"[{label}] {classification.details} {action}"
